import { chromium } from "playwright-core";
import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";
config({ path: ".env.local" });
const EMAIL = `dbg15-${Date.now()}@revdevhqos.dev`;
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const { data: created } = await admin.auth.admin.createUser({ email: EMAIL, password: "dbg-12345678", email_confirm: true, user_metadata: { name: "Dbg" } });
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await (await browser.newContext()).newPage();
page.setDefaultTimeout(20000);
await page.goto("http://localhost:3000/sign-in");
await page.fill('input[name="email"]', EMAIL);
await page.fill('input[name="password"]', "dbg-12345678");
await page.click('button[type="submit"]');
await page.waitForURL("**/setup");
await page.fill('input[name="name"]', "Dbg WS");
await page.click('button[type="submit"]');
await page.waitForURL("**/dashboard");
await page.goto("http://localhost:3000/tasks");
await page.getByRole("button", { name: "Add Task" }).first().click();
await page.fill('input[placeholder="Publish monthly report"]', "Finish homepage revisions");
await page.locator('input[type="checkbox"]').first().check();
const dateVal = await page.locator('input[type="date"]').first().inputValue();
console.log("form scheduledDate value:", dateVal);
await page.getByRole("button", { name: "Create task" }).click();
await page.waitForSelector("text=added to calendar");
await page.goto("http://localhost:3000/tasks");
await page.waitForLoadState("networkidle");
console.log("page URL after nav:", page.url());
await browser.close();
if (created?.user) await admin.auth.admin.deleteUser(created.user.id);
